config/routes.rb
Rails.application.routes.draw do

  resources :cards, only: [:show, :new, :index, :destroy]
  resources :levels, only: [:edit, :update, :create]
  get '/users/:id/newcard', to: 'levels#new', as: 'newcard'

	resources :users
	get '/users/:id/study', to: 'users#study', as: 'study'
  get '/users/:id/cardlist', to: 'users#cardlist', as: 'cardlist'
  put 'cardstates/:id/update', to: 'cardstates#update'

  get 'static_pages/home'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'static_pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
	has_many :cardstates, dependent: :destroy
	has_many :levels, dependent: :destroy
end

app/models/cardstate.rb
class Cardstate < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :card
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def new
  end

  def show
    @card = Card.find(params[:id])
  end

  def edit
    @card = Card.find(params[:id])
  end

  def index
  end

	def destroy
    @card = Card.find(params[:id])
		@card.destroy	
		redirect_to users_path
	end
end

app/controllers/cardstates_controller.rb
class CardstatesController < ApplicationController

  def edit
    @user = User.find(params[:id])
    @nextcard = helpers.getnextcard(@user)
    @questionarray = helpers.separatequestion(@nextcard.card.levels.first.question)
  end

  def update
    @nextcard = Cardstate.find(params[:id]) 
    @user = @nextcard.user
    if cardstate_params[:first] == helpers.separatequestion(@nextcard.card.levels.first.question)["answer"]
      @nextcard.update(successes: @nextcard.successes += 1, lastsuccess: Date.today)
      flash[:message] = 'Correct'
    else
      @nextcard.update(successes: 0, lastsuccess: nil)
      flash[:message] = 'Incorrect'
    end
    redirect_to study_path(@user)
  end

  private

  def cardstate_params
    params.require(:answer).permit(:first)
  end

end

app/controllers/levels_controller.rb
class LevelsController < ApplicationController
  
  def new
    @newlevel = Level.new
  end

  def create
    @user = User.last
    newcard = Card.create
    @newlevel = Level.new(level_params)
    @newlevel.update_attributes(card_id: newcard.id)
    @newlevel.save
    @user.cardstates.create(card_id: newcard.id, successes: -2)
    redirect_to @user
  end

  def edit
    @level = Level.find(params[:id]) 
  end

  def update
    @level = Level.find(params[:id]) 
    if @level.update_attributes(level_params)
      redirect_to @level.card
    end
  end

  private

  def level_params
    params.require(:level).permit(:question)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

	def setup
		@var = "borgon"
	end
	
  def home
		#render html: "this is the word of the day: #{@var}"
  end

  def help
  end

	def about 
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
	def new
		@newuser = User.new
  end
	
	def create
		@newuser = User.create(user_params)
		redirect_to @newuser
	end

	def edit
		@user = User.find(params[:id])
	end

	def update
		@user = User.find(params[:id])
		if @user.update_attributes(user_params)
			redirect_to @user
		end
	end

	def index
		@users = User.all
	end

  def show
    @user = User.find(params[:id])
		helpers.addnewcards(@user)
		@numberofduecards = helpers.getallduecards(@user).count
  end

  def study
		@user = User.find(params[:id])
		if @nextcard = helpers.getnextcard(@user)
      @questionarray = helpers.separatequestion(@nextcard.card.levels.first.question)
    end
  end

  def cardlist
		@user = User.find(params[:id])
  end

	private

	def user_params
		params.require(:user).permit(:name)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/cardstates_helper.rb
module CardstatesHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

	def addnewcards(user)
    if user.laststudied != Date.today && user.cardstates.where(successes: -2).count > 0
			cardsneeded = 15 - user.cardstates.where(successes:-1).count	
			cardsneeded.times do 
				user.cardstates.where(successes: -2).first.update(successes: -1)
			end
		end
    user.update(laststudied: Date.today)
	end

	def getnextcard(user)
    if nextcard = user.cardstates.where(successes: -1).first
			return nextcard
    elsif allcards = user.cardstates.where("successes > ?", -1).order(:updated_at, :id)
      allcards.find{|i| i.lastsuccess.nil? || (i.lastsuccess + i.successes) <= Date.today}
    else
      return nil
		end
	end
	
	def getallduecards(user)
		allcards = user.cardstates.where("successes>= ?", -1)
		allcards.select { |i| i.lastsuccess.nil? || (i.lastsuccess + i.successes) <= Date.today }
	end

	def separatequestion(question)
    output = {}
    output["complete"] = question.split(/(?=\{)|(?<=\})/)
    answer = output["complete"].reject { |i| i[0] != "{" }
    output["answer"] = answer[0][1..-2]
    return output
 	end

	def classifyelement(element)
		if element[0] == "{" && element[-1] == "}"
			return "answer-text"
		else
			return "plaintext"
		end
	end

end

app/views/cards/edit.html.erb
<h1>Cards#edit</h1>

app/views/cards/index.html.erb
<h1>All Cards</h1>
<% Card.all.each do |i| %>
  <p>
	<% if i.levels.exists? %>
		<%= "#{i.id} - #{i.levels.first.question}" %>
	<% end %>
  <%= link_to 'View', card_path(i.id) %> 
  </p>
<% end %>

app/views/cards/new.html.erb
<h1>Cards#new</h1>
<p>Find me in app/views/cards/new.html.erb</p>

app/views/cards/show.html.erb
<h1>View card</h1>
<%= "Card id - #{@card.id}" %>
<% @card.levels.each do |i| %>
  <p><%= i.question %> - <%= link_to 'Edit', edit_level_path(i.id) %> </p> 
<% end %>
<%= link_to "Delete card", @card, method: :delete %>
<%= console %>

app/views/cardstates/edit.html.erb
<h1>Next question</h1>
<p><%= @user.name %></p>
<% @questionarray["complete"].each do |element| %>
	<p> <%= element %> </p>
<% end %>
<p> <%= @nextcard.id %> </p>
<p>
  <%= form_for(@nextcard) do |f| %>
    <%= f.label :successes %>
   	<%= f.text_field :successes %>
    <%= f.submit "Submit Answer", class: "btn btn-primary" %>
  <% end %>
</p>
<%= console %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TeachingApp3</title>
    <% flash.each do |message_type, message| %>
			<% flashcolor = (flash[:message] == "Correct" ? "green" : "red") %>
        <%= content_tag(:div, message, style: "background-color:#{flashcolor}") %>
      <% end %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/levels/edit.html.erb
<h1>Edit the question</h1>
<%= form_for(@level) do |f| %>

  <%= f.label :question %>
  <%= f.text_area :question %>

  <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>

app/views/levels/new.html.erb
<h1>Write the question</h1>
<%= form_for(@newlevel) do |f| %>

  <%= f.label :question %>
  <%= f.text_area :question %>
  <%= f.submit "Save", class: "btn btn-primary" %>

<% end %>
<%= console %>

app/views/static_pages/about.html.erb
<h1>This is the about page</h1>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<%= provide(:title, "Home") %>
<h1>StaticPages#home</h1>
<p>Find me in app/views/static_pages/home.html.erb</p>

app/views/users/cardlist.html.erb
<h1>Full list of cards</h1>
<p><%= link_to 'New Card', newcard_path %></p>
<%= link_to "Back to user", user_path %>
<% @user.cardstates.each do |i| %>
  <% @card = i.card%>
  <p><%= "#{i.id} - #{i.card.levels.first.question}" %>
  <%= link_to 'View', card_path(@card) %></p>
<% end %>

app/views/users/edit.html.erb
<h1>Edit User</h1>
<p>
<%= form_for(@user) do |f| %>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.submit "Create new user", class: "btn btn-primary" %>
<% end %>
</p>

app/views/users/index.html.erb
<h1>All Users</h1>

<ul class="users">
	<% @users.each do |user| %>
		<li>
      <%= link_to user.name, user %>
		</li>
	<% end %>
</ul>

<p>
<%= link_to "New User", new_user_path %>
</p>

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<h1>User Home Page</h1>
<p>
<%= @user.name %> - <%= @user.id %>
</p>
<p>You have <%= @numberofduecards %> cards to study today</p>
<p>You have <%= @user.cardstates.count %> cards in total</p>
<p>You have <%= @user.cardstates.where(successes: -2).count %> cards in your queue</p>
<p><%= link_to 'Study Now', study_path(@user) %> </p> 
<p><%= link_to 'View All My Cards', cardlist_path(@user) %> </p> 
<p><%= link_to 'Edit Profile', edit_user_path(@user) %> </p> 

app/views/users/study.html.erb
<h1>Next question</h1>
<p><%= @user.name %></p>
<% if @questionarray %>
  <% @questionarray["complete"].each do |element| %>
    <p> 
    <% if classifyelement(element) == "answer-text" %>

      <%= form_tag("/cardstates/#{@nextcard.id}/update", method: "put") do %>
        <%= text_field_tag("answer[first]") %>
        <%= submit_tag("Submit Answer") %>
      <% end %>

    <% elsif classifyelement(element) == "plaintext" %> 
      <%= element %>
    <% end %>
    </p>
  <% end %>
  <p> <%= @nextcard.id %> </p>
<% end %>
<%= link_to "Back to user page", @user %>
<%= console %>